spring:
  application:
    name: playground
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 92660482377-8te99ebjq14qa9tb3kuti4jml3k7bjd0.apps.googleusercontent.com
            client-secret: ${RESOURCE-SERVER-CLIENT-SECRET}
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  datasource:
    url: jdbc:h2:mem:playgrounddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
  quartz:
    job-store-type: ${QUARTZ_JOB_STORE_TYPE:jdbc}
    jdbc:
      initialize-schema: ${QUARTZ_JDBC_INITIALIZE_SCHEMA:always}
    properties:
      org:
        quartz:
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: ${QUARTZ_JOB_STORE_IS_CLUSTERED:true}
            useProperties: ${QUARTZ_JOB_STORE_USE_PROPERTIES:true}
            tablePrefix: ${QUARTZ_JOB_STORE_TABLE_PREFIX:QRTZ_}
openapi:
  oAuthFlow:
    authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
    tokenUrl: https://oauth2.googleapis.com/token

springdoc:
  swagger-ui:
    oauth:
      clientId: 92660482377-a852n93ualaq49aiun1lijpq4opmt27m.apps.googleusercontent.com
    oauth2RedirectUrl: http://localhost:8081/swagger-ui/oauth2-redirect.html

# self-signed SSL configuration
server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:playground.jks
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: JKS
    key-alias: playground

gateway:
  settlement:
    FINIQ_SCB:
      HK: 1234
      UK: 5678
    FINIQ_WLB:
      CHN: 31415

app:
  FileExtractor:
    client:
      url: http://localhost:5131/api/

test:
  url: http://localhost:8081/api/test

scheduling:
  jobs:
    pingJob:
      google:
        enabled: true
        cronExpression: "0/30 * * * * ?"
      youtube:
        enabled: true
        cronExpression: "0/30 * * * * ?"
