name: Pull request check

on:
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        uses: .github/workflows/build.yml@ADD_AUTOMATE_SCRIPT
        with:
            java-version: '17'
            distribution: 'temurin'
            
        