name: Deploy Spring boot application

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SERVER_HOST:
        required: true
      SERVER_USER:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact from temp store
        uses: actions/download-artifact@v4
        with:
          name: playground-JAR
          path: target/
      
      - name: Downlaod deployment script from temp store
        uses: actions/download-artifact@v4
        with:
          name: deploy-script
          path: scripts/

      - name: Set up SSH key
        run : |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Install ansible 
        run: sudo apt-get install -y ansible
      
      # TODO: Use ansible to deploy the application